### ISSUE TITLE
freeze 12 pro Max

### ISSUE THREAD

**Issue by kendoss972** [rllbe/weatherdate#2]
the icon size is now fixed,but the freeze still here when i scroll,maybe jetsam memory limits? i don't know,but this tweak is very very good,keep up the good work

**Comment by rllbe** [comment]
I can't reproduce your problem. 
What jailbreak are you using? If you're using unc0ver, you can try adjusting jetsam limit in substrate settings

**Comment by kendoss972** [comment]
I use unc0ver,i already change my Substitute Settings with the jetsam mode (lenient) maybe a issue with a14 device,thanks for the support

**Comment by kendoss972** [comment]
I have the impression that it is a problem with the number of pages,I have 3 pages and when I scroll it freeze,I now have 2 pages on the springboard and it does not freeze anymore,I will temporarily keep this fix

**Comment by rllbe** [comment]
Sorry but I really can't reproduce it.
I'm using an a14 device with default jetsam limits and 4 pages on springboard and never have a freeze. If you have any crash/panic log please upload it for me? Or maybe it's due to a conflict among tweaks. Could you try disabling all other tweaks and only keep this tweak enabled, and see if there's still any freeze?

**Comment by kendoss972** [comment]
i found the guilty tweak thanks,it's zenith tweak,so i delete it,all good now
